# Generated by Django 4.1.1 on 2022-09-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CodeChef',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField()),
                ('global_rank', models.PositiveIntegerField()),
                ('country_rank', models.PositiveIntegerField()),
                ('no_of_contests', models.PositiveIntegerField()),
                ('number_of_problems_solved', models.PositiveIntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='CodeForces',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('contest_rating', models.PositiveIntegerField(null=True)),
                ('maximum_rating', models.PositiveIntegerField(null=True)),
                ('number_of_problems', models.PositiveIntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='GitHub',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('codeforces_username', models.CharField(max_length=255)),
                ('codechef_username', models.CharField(max_length=255)),
                ('leetcode_username', models.CharField(max_length=255)),
                ('hackerrank_username', models.CharField(max_length=255)),
                ('github_username', models.CharField(max_length=255)),
                ('linkedin_username', models.CharField(max_length=255)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
            ],
        ),
    ]
