# Generated by Django 4.1.7 on 2023-02-18 16:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(13)])),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=1)),
                ('codeforces_username', models.CharField(max_length=255, unique=True)),
                ('codechef_username', models.CharField(max_length=255, unique=True)),
                ('leetcode_username', models.CharField(max_length=255, unique=True)),
                ('hackerrank_username', models.CharField(max_length=255, unique=True)),
                ('github_username', models.CharField(max_length=255, unique=True)),
                ('linkedin_username', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeChefDetail',
            fields=[
                ('rating', models.PositiveIntegerField()),
                ('highest_rating', models.PositiveIntegerField()),
                ('global_rank', models.CharField(max_length=50)),
                ('country_rank', models.CharField(max_length=50)),
                ('no_of_contests', models.PositiveIntegerField()),
                ('number_of_problems_solved', models.PositiveIntegerField()),
                ('division', models.CharField(max_length=255)),
                ('star_rating', models.PositiveSmallIntegerField()),
                ('partially_solved_questions', models.PositiveIntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='CodeForcesDetail',
            fields=[
                ('tag', models.CharField(max_length=255)),
                ('current_rating', models.PositiveIntegerField(null=True)),
                ('maximum_rating', models.PositiveIntegerField(null=True)),
                ('number_of_problems_solved', models.PositiveIntegerField(null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubDetail',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('number_of_repos', models.PositiveIntegerField()),
                ('valid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeetCodeDetail',
            fields=[
                ('general_rank', models.BigIntegerField()),
                ('easy', models.PositiveIntegerField()),
                ('medium', models.PositiveIntegerField()),
                ('hard', models.PositiveIntegerField()),
                ('participated_in_contests', models.BooleanField()),
                ('contest_rank', models.PositiveBigIntegerField()),
                ('number_of_contests', models.PositiveIntegerField()),
                ('contest_rating', models.PositiveIntegerField()),
                ('familiar_languages', models.CharField(max_length=255)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
            ],
        ),
    ]
