# Generated by Django 4.1.1 on 2022-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
