# Generated by Django 4.1.3 on 2022-11-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechefdetail',
            name='country_rank',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='codechefdetail',
            name='global_rank',
            field=models.CharField(max_length=50),
        ),
    ]
