# Generated by Django 4.1.3 on 2022-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hackerrank_username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='leetcode_username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin_username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
