# Generated by Django 4.1.3 on 2022-11-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_hackerrank_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hackerrank_username',
            field=models.CharField(default='-', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='leetcode_username',
            field=models.CharField(default='-', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin_username',
            field=models.CharField(default='-', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
