# Generated by Django 4.1.1 on 2022-09-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_name_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registration_number',
            new_name='id',
        ),
    ]
