# Generated by Django 4.1.1 on 2022-09-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_registration_number_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codechef',
            name='username',
        ),
        migrations.RemoveField(
            model_name='codeforces',
            name='username',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='username',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='username', serialize=False, to='students.student'),
        ),
        migrations.DeleteModel(
            name='GitHub',
        ),
    ]
