# Generated by Django 4.1.1 on 2022-09-25 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_codechef_username_remove_codeforces_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usernames', serialize=False, to='students.student'),
        ),
    ]
