# Generated by Django 4.1.1 on 2022-09-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_username_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHub',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('number_of_repos', models.SmallIntegerField()),
            ],
        ),
    ]
