# Generated by Django 4.1.1 on 2022-09-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeforces',
            name='number_of_problems',
        ),
        migrations.AddField(
            model_name='codeforces',
            name='number_of_problems_solved',
            field=models.CharField(default='-', max_length=40),
            preserve_default=False,
        ),
    ]
