# Generated by Django 4.1.1 on 2022-09-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_codeforces_number_of_problems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeforces',
            old_name='contest_rating',
            new_name='current_rating',
        ),
    ]
