# Generated by Django 4.1.1 on 2022-09-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_contest_rating_codeforces_current_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechef',
            name='country_rank',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='codechef',
            name='global_rank',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='codechef',
            name='number_of_problems_solved',
            field=models.CharField(max_length=50),
        ),
    ]
