# Generated by Django 4.1.1 on 2022-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_codechef_country_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechef',
            name='country_rank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codechef',
            name='global_rank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codechef',
            name='rating',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codeforces',
            name='number_of_problems_solved',
            field=models.CharField(max_length=60),
        ),
    ]
