# Generated by Django 4.1.1 on 2022-10-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_codechef_country_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codechef',
            name='division',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codechef',
            name='highest_rating',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codechef',
            name='partially_solved_questions',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codechef',
            name='star_rating',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codechef',
            name='no_of_contests',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codechef',
            name='number_of_problems_solved',
            field=models.CharField(max_length=255),
        ),
    ]
