# Generated by Django 4.1.1 on 2022-10-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_codechef_division_codechef_highest_rating_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeChef',
            new_name='CodeChefDetail',
        ),
        migrations.RenameModel(
            old_name='CodeForces',
            new_name='CodeForcesDetail',
        ),
        migrations.RenameModel(
            old_name='GitHub',
            new_name='GitHubDetail',
        ),
    ]
