# Generated by Django 4.1.1 on 2022-10-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_rename_codechef_codechefdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubdetail',
            name='number_of_repos',
            field=models.CharField(max_length=50),
        ),
    ]
