# Generated by Django 4.1.1 on 2022-10-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_id_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
