# Generated by Django 4.1.1 on 2022-10-08 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
