# Generated by Django 4.1.1 on 2022-10-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
