# Generated by Django 4.1.2 on 2022-10-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='codechef_username',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='codeforces_username',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='github_username',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='hackerrank_username',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='leetcode_username',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_username',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
