# Generated by Django 4.1.2 on 2022-11-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_student_codechef_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechefdetail',
            name='country_rank',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='codechefdetail',
            name='global_rank',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='codechefdetail',
            name='highest_rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='codechefdetail',
            name='number_of_problems_solved',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='codechefdetail',
            name='partially_solved_questions',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='codechefdetail',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='codechef_username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='codeforces_username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='github_username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hackerrank_username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='leetcode_username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin_username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
