# Generated by Django 4.1.2 on 2022-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_alter_codechefdetail_country_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeforcesdetail',
            name='number_of_problems_solved',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
