# Generated by Django 4.1.2 on 2022-11-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_codeforcesdetail_number_of_problems_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubdetail',
            name='valid',
            field=models.CharField(default='o', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubdetail',
            name='number_of_repos',
            field=models.PositiveIntegerField(),
        ),
    ]
