# Generated by Django 4.1.2 on 2022-11-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_githubdetail_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubdetail',
            name='valid',
            field=models.CharField(max_length=20),
        ),
    ]
