# Generated by Django 4.1.2 on 2022-11-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_alter_githubdetail_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechefdetail',
            name='no_of_contests',
            field=models.PositiveIntegerField(),
        ),
    ]
